<?xml version="1.0" encoding="utf-8"?><Database Name="NFL" Class="NFLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\NFL.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="NFLConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Player" Member="Players">
    <Type Name="Player">
      <Column Name="PlayerId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PlayerPoS" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="PlayerNumber" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="PlayerName" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="PlayerStatus" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="statisticsId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Statistic_Player" Member="Statistics" ThisKey="statisticsId" OtherKey="StatisticsId" Type="Statistics" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Statistics]" Member="Statistics">
    <Type Name="Statistics">
      <Column Name="StatisticsId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TeamOrPlayer" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Wins" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Losses" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Rank" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Association Name="Statistic_Player" Member="Players" ThisKey="StatisticsId" OtherKey="statisticsId" Type="Player" />
      <Association Name="Statistic_Team" Member="Teams" ThisKey="StatisticsId" OtherKey="statisticsId" Type="Team" />
    </Type>
  </Table>
  <Table Name="dbo.Team" Member="Teams">
    <Type Name="Team">
      <Column Name="TeamId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TeamPoS" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="TeamNumber" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="TeamName" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="TeamStatus" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="statisticsId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PlayerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Statistic_Team" Member="Statistics" ThisKey="statisticsId" OtherKey="StatisticsId" Type="Statistics" IsForeignKey="true" />
    </Type>
  </Table>
</Database>